#!/usr/bin/env python3

import os.path

import plotly.graph_objects as go
import pandas as pd
import numpy as np

import dataBuilder

def isReadable():
    reducedDB = '_data.npy'
    if not os.path.isfile(reducedDB):
        dataBuilder.buildData()


def main():
    isReadable()

    df = np.load("data.npy")
    print(df)

    fig = go.Figure(data=
        go.Parcoords(
            line = dict(color = df['Year'],
                    colorscale = 'Electric',
                    showscale = True,
                    cmin = 1900,
                    cmax = 2020),
            dimensions = list([
                dict(label = 'Medal', values = df['Medal']),
                dict(label = "Country", values = df['Team']),
                dict(label = 'Sport', values = df['Sport']),
                dict(label = 'Year', values = df['Year']),
            ])
        )
    )
    fig.show()


if __name__ == "__main__":
    main()